#!/usr/bin/env python3
#
# Jailhouse, a Linux-based partitioning hypervisor
#
# Copyright (c) MediaTek Inc., 2026
#
# Authors:
#  Aary Patil <aary.patil@mediatek.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#
# Generates hypervisor/arch/arm64/mt8188-iocfg.c, the pin configuration
# (IOCFG) fields of MT8188, from the PIN_FIELD_BASE tables in Linux's
# drivers/pinctrl/mediatek/pinctrl-mt8188.c.
#
# usage: gen-mt8188-iocfg.py <pinctrl-mt8188.c> > mt8188-iocfg.c

import re
import sys
from collections import defaultdict

# Linux's i_base index -> name, address of the block
BLOCKS = {
    1: ("iocfg_rm", 0x11c00000),
    2: ("iocfg_lt", 0x11e10000),
    3: ("iocfg_lm", 0x11e20000),
    4: ("iocfg_rt", 0x11ea0000),
}
BLOCK_SIZE = 0x1000
# tables of the GPIO block itself (i_base 0), or no register fields
SKIP = {"mode", "dir", "di", "do", "rsel_val"}

HEADER = """\
/*
 * Jailhouse, a Linux-based partitioning hypervisor
 *
 * Copyright (c) MediaTek Inc., 2026
 *
 * MT8188 pin configuration (IOCFG) fields
 *
 * Generated by scripts/gen-mt8188-iocfg.py from Linux's
 * drivers/pinctrl/mediatek/pinctrl-mt8188.c. Do not edit.
 *
 * This work is licensed under the terms of the GNU GPL, version 2.  See
 * the COPYING file in the top-level directory.
 */

#include <jailhouse/utils.h>
#include <asm/mediatek.h>
"""


def parse(path):
    fields = defaultdict(list)  # (i_base, offset) -> [(pin, shift, width)]
    src = open(path).read()
    for m in re.finditer(r"mt8188_pin_(\w+)_range\[\] = \{(.*?)\n\};",
                         src, re.S):
        if m.group(1) in SKIP:
            continue
        for e in re.finditer(r"PIN_FIELD_BASE\(([^)]*)\)", m.group(2)):
            s_pin, e_pin, i_base, s_addr, x_addrs, s_bit, x_bits = \
                [int(v, 0) for v in e.group(1).split(",")]
            if i_base not in BLOCKS:
                sys.exit("unknown block in " + e.group(0))
            for pin in range(s_pin, e_pin + 1):
                bit = s_bit + (pin - s_pin) * x_bits
                shift = bit % 32
                if shift + x_bits > 32 or pin > 255:
                    sys.exit("unsupported field in " + e.group(0))
                fields[(i_base, s_addr + bit // 32 * x_addrs)].append(
                    (pin, shift, x_bits))

    # Fields of different pins may only overlap if they are the same field,
    # shared by these pins (e.g. one SMT bit for a group of pins).
    for key, fl in fields.items():
        masks = set()
        for pin, shift, width in fl:
            mask = ((1 << width) - 1) << shift
            if any(m & mask and m != mask for m in masks):
                sys.exit("partially overlapping fields at %s" % (key,))
            masks.add(mask)
    return fields


def wrap(items, indent):
    lines, line = [], indent
    for item in items:
        if len(line.expandtabs()) + len(item) + 1 > 80:
            lines.append(line.rstrip())
            line = indent
        line += item + " "
    lines.append(line.rstrip())
    return lines


def main():
    fields = parse(sys.argv[1])
    out = [HEADER]
    for i_base, (name, phys) in BLOCKS.items():
        regs = sorted(o for (b, o) in fields if b == i_base)
        out.append("static const struct mtk_pin_field %s_fields[] = {" % name)
        first, n = {}, 0
        for offset in regs:
            first[offset] = n
            fl = sorted(fields[(i_base, offset)], key=lambda f: (f[1], f[0]))
            out.append("\t/* %#05x */" % offset)
            out += wrap(["{ %d, %d, %d }," % f for f in fl], "\t")
            n += len(fl)
        out.append("};\n")
        out.append("static const struct mtk_field_reg %s_regs[] = {" % name)
        for offset in regs:
            out.append("\t{ %#05x, %d, %d }," %
                       (offset, first[offset], len(fields[(i_base, offset)])))
        out.append("};\n")

    out.append("const struct mtk_window mt8188_iocfg[%d] = {" % len(BLOCKS))
    for name, phys in BLOCKS.values():
        out += ["\t{",
                "\t\t.phys = %#x," % phys,
                "\t\t.size = %#x," % BLOCK_SIZE,
                "\t\t.regs = %s_regs," % name,
                "\t\t.num_regs = ARRAY_SIZE(%s_regs)," % name,
                "\t\t.fields = %s_fields," % name,
                "\t},"]
    out.append("};")
    print("\n".join(out))


main()
