#
# Jailhouse AArch64 support
#
# Copyright (C) 2015 Huawei Technologies Duesseldorf GmbH
# Copyright (c) Siemens AG, 2016
#
# Authors:
#  Antonios Motakis <antonios.motakis@huawei.com>
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

include $(src)/../arm-common/Kbuild

always-y := lib.a

# units initialization order as defined by linking order:
# irqchip (common-objs-y), <generic units>

lib-y := $(common-objs-y)
lib-y += entry.o setup.o control.o mmio.o paging.o caches.o traps.o
lib-y += iommu.o smmu-v3.o ti-pvu.o
lib-y += smmu.o

# MediaTek clock gate, EINT and GPIO units: their engines (mtk-common*) and
# the tables of the SoC that CONFIG_SOC names (mtk-<soc>-*); without
# CONFIG_SOC, the hypervisor has no such units
ifneq ($(CONFIG_SOC),)
lib-y += mtk-common.o mtk-common-clk.o mtk-common-eint.o mtk-common-gpio.o
endif

ifeq ($(CONFIG_SOC),mt8188)
lib-y += mtk-mt8188-clk.o mtk-mt8188-eint.o mtk-mt8188-gpio.o
else ifneq ($(CONFIG_SOC),)
$(error CONFIG_SOC=$(CONFIG_SOC) is not supported, use CONFIG_SOC=mt8188)
endif
